name: hello-from-hexlet-action

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Укажите желаемую версию Node.js

      - name: Install dependencies
        run: |
          npm install

      - name: Hello from Hexlet
        uses: hexlet-components/hello-from-hexlet-action@release

      - name: Run tests
        run: |
          npm test
